-- MySQL Script generated by MySQL Workbench
-- Thu Aug 30 00:13:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cuzcuzDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cuzcuzDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuzcuzDB` DEFAULT CHARACTER SET utf8 ;
USE `cuzcuzDB` ;

-- -----------------------------------------------------
-- Table `cuzcuzDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuzcuzDB`.`Users` (
  `idUser` VARCHAR(8) NOT NULL,
  `pw_user` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuzcuzDB`.`Notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuzcuzDB`.`Notes` (
  `idNote` INT NOT NULL,
  `content` TEXT(500) NOT NULL,
  PRIMARY KEY (`idNote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuzcuzDB`.`User_Notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuzcuzDB`.`User_Notes` (
  `idUser` VARCHAR(8) NOT NULL,
  `idNote` INT NOT NULL,
  INDEX `idNote_Notes_idNote_idx` (`idNote` ASC),
  CONSTRAINT `idUser_Users_idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `cuzcuzDB`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idNote_Notes_idNote`
    FOREIGN KEY (`idNote`)
    REFERENCES `cuzcuzDB`.`Notes` (`idNote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
